baseURL = "https://www.kli.dk/"
theme = "cactus"
disablePathToLower = true
languageCode = "en-us"
title = "Mads Klinkby's weblog"
copyright = "Klinkby"

[params]

  colortheme = "light"
  description = "Independent Enterprise + Office 365 Solution Architect & full stack dev with head in the cloud and feet on the ground."
  mainSection = "posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
 # tagsOverview = true
  showProjectsList = true
  projectsUrl = "https://github.com/klinkby"
  rss = true

  [[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/klinkby/"

  [[params.social]]
  name = "github"
  link = "https://github.com/klinkby"

  [[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/klinkby/"

